- How to print in python.md
> Create How to print in python.md

- reverse_list_in_python.md
> Add: reverse list in python

- How to reverse a string in python.md
> How to reverse a string in python

- How to add two lists in python.md
> How to add two lists in python

- How to add two lists in python.md
- How to count list element frequency in python.md
- String example in python.md
> List count

- How to add two lists in python.md
- How to clone list in python.md
- How to count list element frequency in python.md
- String example in python.md
- find index of element in python list.md
> Index list

- how_to_use_join_in_python.md
Using join in python using a simple function
> Added how to use join in Python

- How to join in python.md
> Tutorial on how to use join in python

- while loop in python.md
> Create while loop in python.md

- index of a string.md
I have found an index of string in python for the issue #30
> Create index of a string.md

- README.md
Added Added "How to add two lists in python"
> 53 - Added "How to add two lists in python"

- README.md
> Added "Variables in Python" link

- Basics of Dictionary.md
> Added a file for basics of dictionary

- README.md
> #54 - Updated Readme

- README.md
- lambda Function.md
> Added a file for lambda functions

- how-to-install-python.md
This PR adds the installation guide of python 3
fix https://github.com/avsingh999/Python-for-beginner/issues/3
> added how-to-install-python.md

- How to plot a graph in python.md
> Added Readme for How to plot graph in python

- Read_write_Python.md
> Added Read and write tutorial in python

- Read_and_Write_Files_in_Python.md
> Added read_and_write_files_in_python.md

- merge_sort_in_python.py
> added merge sort in python

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Added bug report and feature request templating.

- LinkedList.py
> adding LinkedList.py

- binary_search_tree_in_python.py
- bubble_sort_in_python.py
> Added binary search tree in python

- heap sort in python.md
> [Issue #91] Added heap sort

- Radix Sort in Python
> Create Radix Sort in Python

- how to read arduino data in python.md
> Added how to read arduino data in python.md resolve #78

- quickSort.md
wrote quicksort algorithm in python in quickSort.md file.
fix #92
> added quickSort.md file

- quicksort_in_python.md
I am writing a small program in Python to do the quick sort algorithm https://github.com/avsingh999/Python-for-beginner/issues/92
> Fix #92: quicksort algorithm in python

- Regex in Python.md
added Regex in Python.md 
fix #108
> Regex in Python.md

- merge sort in python.md
> [Issue #90] Added merge sort

- how to plot a graph in python
- how to read data from arduino.md
> how to read data from arduino

- Insertion sort in python.md
> [Issue #89] Added insertion sort

- BinarySearch.md
write binary search algorithm in python and saved it in a file named BinarySearch.md
fix #86
> created BinarySearch.md file

- how-to-beautifulsoup.md
> add How To BeautifulSoup

- How to do fibbonacci.md
Added how-to fibbonacci and a little bit of explanation about what fibonacci sequence is.
Happy Coding!
> Added how-to fibonacci sequence

- request in python.md
> Python Http Request

- How to do http request in python.md
- simple gui in tkinter python.md
> Adding add info about https request in python

- tkinter.md
> Radio Buttons

- sum_range_1d_array.md
> Added code for sum in 1d array

- How to print in python.md
> Update How to print in python.md

- README.md
- segment_tree_implementaion_in_python.md
> Add segment tree description and implementation in python

- segment tree implementation in python.md
> issue #127: segment tree implementation

- Basic Operations
:heart: Python Code that Displays Addition, Substraction, Division and Multiplication of 2 numbers :heart:
> Create Basic Operations

- Introducing_DataFrame_and_Cleaning_NaN_values.md
- how to use tkinter library for python.md
Pull request to add a file about Data Frame and missing values NaN #44
> Added file to Introducing_DataFrame_and_Cleaning_NaN_values.md

- How to read and write csv files in python.md
> Add csv examples

- Try-Except method
Created a new tutorial file on Try_Except Method. I want people to edit it further and make the file better. I have added an example of ValueError. We can also add the "raise" in the same file.
> Create Try_Except Method

- README.md
- how to catch exceptions in python.md
Fix #165.
Happy to help, this is fun.
> Created a try-except quick tutorial

- Tuples in Python
> Create Tuples in Python

- README.md
- algorithms/euclidean_gcd.py
- algorithms/nested_brackets.py
- algorithms/two_sum.py
added an algorithem 
also made some grammatical changes in readme file
> #156:algorithem and small change in readme

- Insertion sort
> Insertion sort

- read_write_json_files.md
> Read and write json

- README.md
These are some edits related to grammar and style for the ReadMe file.
I did not see an issue related to this
> Grammatical and stylistic adjsutments README

- random_number_in_a_range.py
> random number How to print random number in a range python added

- for loop in python.md
- Program to find the sum of all numbers stored in a list
- List of numbers
numbers = list(range(1,  17))
- iterate over the list
sum(numbers)
- Output: The sum is 48
print("Sum is", sum)
fix #00
> Create for loop in python.md

- Find if the number is odd or even.md
fix #191 
A python program to find if the given number is odd or even
>  a python program to find if the given number is odd or even

- Sets in python
> Available set methods added

- DFS algo
- Generate a Random Number in python
- Python Program to Generate a Random Number
> Python Program to Generate a Random Number

- How_to_print_a_random_number.py
> Added file showing how to print a random integer between two integers

- BFS implemetation
- generating random numbers
> generating random numbers

- how to print random number in a range python.py
fix #00
this is a python file, so there is an example of the function and description.
> how to print random number in a given range added!

- topics/read-write-JSON-files/data.json
- topics/read-write-JSON-files/read-write-json-file.py
#178 Added read-write-json-file
> Added read-write-json-file

- Password generator in python.md
fix #207 
Issue no #207 fixed.
> Generate password of 8 charcter long

- Connect to github using socket.md
fix #211 
Socket program to connect to github.com
> python program to connect to github.com using socket

- Python Date Time/datetime
- Python Date Time/readme.md
- Python Date Time/time_in_python.py
> Time in Python

- Password generator in python.md
Markdown was not proper before in this .md file, so i updated the markdown to make code look proper
> Codes properly formated

- Find if the number is odd or even.md
- how to find if a number is prime.md
> Pull Request

- DFS.py
> DFS in PYTHON ADDED

- program to reverse a string.py
> Create program to reverse a string

- pycodemathlib.py
> Example of math library in python

- math_functions.py
- maths_func.py
> Maths functions

- How to get user input and display it
> How to get user input and display it

- diamond_pattern.py
Added the code for user input based diamond Pattern
fix #233
> Print Diamond Pattern in Python

- prim's-algo-py.py
Created a python implementation of prim's algorithm,
> Create prim's algorithm

- Diamond Star Pattern.py
> added Diamond Star Pattern

- RankSort_in_python.py
> added ranksort in python

- Print A pattern by input row.py
> Create Print A pattern by input row

- algorithms/sieve_of_eratosthenes.py
Example of generating primes using sieve of Eratosthenes algorithm.
> Add: Sieve of Eratosthenes prime generator.

- How to print in python.md
> How to use print function with variables.

- README.md
- SieveOfEratosthenes.py
> Added Code for Sieve of Eratosthenes

- simple_socket_client.py
- simple_socket_server.py
I had added two files Socket Client and Socket Server
> Socket Programming for beginners

- Socket_Client_Server_text.md
I had add one text document for client and server python programming
> Documentation for scoket programming

- algorithms/HeapSort.py
> Added HeapSort.py file

- Positive or Negative number.md
> Positive or Negative

- LearnWebWithFlask/Introduction.md
- LearnWebWithFlask/index.py
- LearnWebWithFlask/templates/aboutFlask.html
> Learning Flask

- nextPrimeOfANumber.py
> Added nextPrimeOfANumber.py

- Find if a number is prime or non-prime(OPTIMIZED).md
> added optimized isPrime method

- LearnWebWithFlask/index.py
- LearnWebWithFlask/login.html
> Adding A Login Page using Flask

- deep copy in python.md
- deep copy in python.py
- shallow copy in ptyhon.md
- shallow copy in python.py
Hi, @avsingh999. I have added Deep and Shallow Copy in Python. 
Please Check my PR, and merge to master.
fix #276 
Happy Hacktoberfest🥳🤓
> Added deep and shallow copy in Python

- Scheduler.py
Solved Issue  #272 
Added a Simple Schedule Event Program as Requested.
> Created Scheduler.py

- Find if a number is prime or non-prime(OPTIMIZED).md
I improved the functionality of the **isPrime** Function to **return Boolean values** instead of just printing them **so that it can also be used on other cases** (i.e. if-else statements and while loops). This also compliments to printing True or False values. Also, I **changed the capitalization** of the **isPrime** Function to **Camel Case** just to cope up with the common convention🙂.
> Improved the Functionality of isPrime Function.
